name: Pipeline o1

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print URL
        run: echo "Teste $URL"
      - name: Print Senha
        run: echo "Teste ${{secrets.SENHA}}"
        
    
    
